export default {
login: "JunaidRathore",
id: 66040197,
node_id: "MDQ6VXNlcjY2MDQwMTk3",
avatar_url: "https://avatars.githubusercontent.com/u/66040197?v=4",
gravatar_id: "",
url: "https://api.github.com/users/JunaidRathore",
html_url: "https://github.com/JunaidRathore",
followers_url: "https://api.github.com/users/JunaidRathore/followers",
following_url: "https://api.github.com/users/JunaidRathore/following{/other_user}",
gists_url: "https://api.github.com/users/JunaidRathore/gists{/gist_id}",
starred_url: "https://api.github.com/users/JunaidRathore/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/JunaidRathore/subscriptions",
organizations_url: "https://api.github.com/users/JunaidRathore/orgs",
repos_url: "https://api.github.com/users/JunaidRathore/repos",
events_url: "https://api.github.com/users/JunaidRathore/events{/privacy}",
received_events_url: "https://api.github.com/users/JunaidRathore/received_events",
type: "User",
site_admin: false,
name: "Muhammad Junaid Rathore",
company: "RjM Logics & Solutuions",
blog: "junaid-rathore.netlify.app",
location: "Pakistan",
email: null,
hireable: null,
bio: "Web Enthusiastic | React.js Developer",
twitter_username: "MrRathoreRJM",
public_repos: 11,
public_gists: 0,
followers: 1,
following: 1,
created_at: "2020-05-27T22:15:30Z",
updated_at: "2021-08-16T13:40:00Z"
}
